### PR TITLE
Feature/6 linter rules

### PR DESCRIPTION
**Pull request by atlesque**
I fixed all the files to comply with the linter rules. Because there are a lot of changes to your code too @Andrew1431 , can you please check if I didn't break anything? 😋 Thanks!

Just running the code and checking if auto-solver still works should be enough I think! I'll try it out myself too 🕵️ 

Fixes https://github.com/atlesque/starfield-digipick-solver/issues/6

### CODE REVIEW

**Comment by atlesque** [comment]
Tested myself with a challenge from a screenshot and it solved it without errors!

Now to test it in-game...

**Review by Andrew1431 — APPROVED** [review]
Tested locally, everything working as expected!

**Comment by Andrew1431** [comment]
If you type "Fixes <issue link>", when you merge this PR it will auto-close the related issue when merged!

**Comment by atlesque** [comment]
> If you add "Fixes <issue link>" to your PR description, when you merge this PR it will auto-close the related issue when merged!

Does it have to be in the PR title / description? I've put it inside one of the commit descriptions that's part of this PR. If it only works in PR title, I'll add it in future too, thx!

**Pull request merged**
