### PR TITLE
[optional] feat: add discord link

### PR DESCRIPTION
**Pull request by Andrew1431**
Add a discord link to the footer.

Fixes https://github.com/atlesque/starfield-digipick-solver/issues/15

### CODE REVIEW

**Comment by Andrew1431** [comment]
> ## Deploying with  [Cloudflare Pages](https://pages.dev)  Cloudflare Pages
> **Latest commit:**	`912eb7f`
> **Status:**	 ✅  Deploy successful!
> **Preview URL:**	https://07606a29.starfield-digipick-solver.pages.dev
> **Branch Preview URL:**	https://feat-discord.starfield-digipick-solver.pages.dev
> [View logs](https://dash.cloudflare.com/?to=/:account/pages/view/starfield-digipick-solver/07606a29-804d-494b-8a9d-f6779a6bf6b5)

oh this is sick what the heck!

**Comment by atlesque** [comment]
Haha what, @Andrew1431 did you add the bot? So now we have preview branches 😁

**Comment by atlesque** [comment]
For Discord, absolutely, good idea! I'll join up!

**Review by atlesque — APPROVED** [review]

**Comment by Andrew1431** [comment]
I didn't do any of that! It's awesome that we can preview PRs before deploying.

**Pull request merged**
